version: 2.1

jobs:
  install-dependencies:
    resource_class: xlarge
    docker:
      - image: node:16-alpine
    steps:
      - checkout
      - restore_cache:
          name: Restore NPM packages cache
          keys:
            - deps-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: |
            if [[ -d node_modules ]]; then
                    exit 0
            fi
            npm ci
      - save_cache:
          key: deps-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

  build-storefront:
    resource_class: xlarge
    docker:
      - image: node:16-alpine
    steps:
      - checkout
      - restore_cache:
          name: Restore NPM packages cache
          keys:
            - deps-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Build demo storefront
          command: |
            CI=false
            npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build

  deploy-demo-storefront:
    resource_class: xlarge
    docker:
      - image: amazon/aws-cli
    steps:
      - run:
          name: Install tar utility
          command: yum install -y tar gzip
      - attach_workspace:
          at: .
      - run:
          name: Upload website to the S3 bucket
          command: aws s3 sync build/ s3://demo.hypermint.com/

  deploy-example-storefront:
    resource_class: xlarge
    docker:
      - image: amazon/aws-cli
    steps:
      - run:
          name: Install tar utility
          command: yum install -y tar gzip
      - attach_workspace:
          at: .
      - run:
          name: Upload website to the S3 bucket
          command: aws s3 sync build/ s3://storefront.hypermint.com/

workflows:
  build-deploy-demo:
    jobs:
      - install-dependencies:
          filters:
            branches:
              only: main
      - build-storefront:
          requires:
            - install-dependencies
      - deploy-demo-storefront:
          context: aws-config
          requires:
            - build-storefront

  build-deploy-example:
    jobs:
      - install-dependencies:
          filters:
            branches:
              only: example
      - build-storefront:
          requires:
            - install-dependencies
      - deploy-example-storefront:
          context: aws-config
          requires:
            - build-storefront

